name: casing-em-cuevas-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - mkl
  - pip:
    - pymatsolver
    - SimPEG
    - git+https://github.com/simpeg-research/casingSimulations.git
